spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/testdb?useSSL=FALSE"
    username: "root"
    password: "qaz88x"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    hibernate:
      ddl-auto: "create"
app:
  jwt:
    expirationMs: "86400000"
    secret: "ufGJqqC94OBE8qJFigbB55Pf2mLCXUDomQKP87qaGl/Nj9b/aWOlvtJ+bBtggH9XnBHR4M7SBtGOq++XfXw0iw=="
